### ISSUE TITLE
Web height calculation bug

### ISSUE THREAD

**Issue by fermenen** [fermenen/lupax#10]
Web Height Calculation failure, grey background not visible.
![Opera Instantánea_2023-03-30_190612_www lupax app](https://user-images.githubusercontent.com/32095133/229348130-85e97524-4586-46e8-8f4d-80ce794f7a28.png)

**Comment by Shubham-2899** [comment]
Hi @fermenen 
![image](https://user-images.githubusercontent.com/85818959/229603976-0d9cd19d-5ebd-44c1-9244-2a09db1b89c2.png)

**Comment by fermenen** [comment]
merged!
