### ISSUE TITLE
Improve contrast card price

### ISSUE THREAD

**Issue by fermenen** [fermenen/lupax#4]
Improve the contrast of the price card (https://www.lupax.app/pricing), with a white color.

![Opera Snapshot_2023-03-29_160710_localhost](https://user-images.githubusercontent.com/32095133/228564751-6b5285e1-aa41-450a-8630-687cd1fd89f8.png)

**Comment by TheAayushRana** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/69390908/228758602-6b58ed52-c820-418d-ae60-5ec22bc636ad.png)

**Comment by fermenen** [comment]
yes, completely. I think this improve a lot the pricing page. Do yoy think the same?
let's talk by discord for to have clear the gitflow
